/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizLessonIdRouteImport } from './routes/quiz.$lessonId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as CompletionLessonIdRouteImport } from './routes/completion.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizLessonIdRoute = QuizLessonIdRouteImport.update({
  id: '/quiz/$lessonId',
  path: '/quiz/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletionLessonIdRoute = CompletionLessonIdRouteImport.update({
  id: '/completion/$lessonId',
  path: '/completion/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completion/$lessonId': typeof CompletionLessonIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/quiz/$lessonId': typeof QuizLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completion/$lessonId': typeof CompletionLessonIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/quiz/$lessonId': typeof QuizLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completion/$lessonId': typeof CompletionLessonIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/quiz/$lessonId': typeof QuizLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completion/$lessonId'
    | '/lesson/$lessonId'
    | '/quiz/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/completion/$lessonId' | '/lesson/$lessonId' | '/quiz/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/completion/$lessonId'
    | '/lesson/$lessonId'
    | '/quiz/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletionLessonIdRoute: typeof CompletionLessonIdRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  QuizLessonIdRoute: typeof QuizLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$lessonId': {
      id: '/quiz/$lessonId'
      path: '/quiz/$lessonId'
      fullPath: '/quiz/$lessonId'
      preLoaderRoute: typeof QuizLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completion/$lessonId': {
      id: '/completion/$lessonId'
      path: '/completion/$lessonId'
      fullPath: '/completion/$lessonId'
      preLoaderRoute: typeof CompletionLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletionLessonIdRoute: CompletionLessonIdRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  QuizLessonIdRoute: QuizLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
