/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompletionRouteImport } from './routes/completion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizDayIdRouteImport } from './routes/quiz.$dayId'
import { Route as LessonDayIdRouteImport } from './routes/lesson.$dayId'

const CompletionRoute = CompletionRouteImport.update({
  id: '/completion',
  path: '/completion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizDayIdRoute = QuizDayIdRouteImport.update({
  id: '/quiz/$dayId',
  path: '/quiz/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonDayIdRoute = LessonDayIdRouteImport.update({
  id: '/lesson/$dayId',
  path: '/lesson/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completion': typeof CompletionRoute
  '/lesson/$dayId': typeof LessonDayIdRoute
  '/quiz/$dayId': typeof QuizDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completion': typeof CompletionRoute
  '/lesson/$dayId': typeof LessonDayIdRoute
  '/quiz/$dayId': typeof QuizDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completion': typeof CompletionRoute
  '/lesson/$dayId': typeof LessonDayIdRoute
  '/quiz/$dayId': typeof QuizDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/completion' | '/lesson/$dayId' | '/quiz/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/completion' | '/lesson/$dayId' | '/quiz/$dayId'
  id: '__root__' | '/' | '/completion' | '/lesson/$dayId' | '/quiz/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletionRoute: typeof CompletionRoute
  LessonDayIdRoute: typeof LessonDayIdRoute
  QuizDayIdRoute: typeof QuizDayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/completion': {
      id: '/completion'
      path: '/completion'
      fullPath: '/completion'
      preLoaderRoute: typeof CompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$dayId': {
      id: '/quiz/$dayId'
      path: '/quiz/$dayId'
      fullPath: '/quiz/$dayId'
      preLoaderRoute: typeof QuizDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$dayId': {
      id: '/lesson/$dayId'
      path: '/lesson/$dayId'
      fullPath: '/lesson/$dayId'
      preLoaderRoute: typeof LessonDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletionRoute: CompletionRoute,
  LessonDayIdRoute: LessonDayIdRoute,
  QuizDayIdRoute: QuizDayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
